### ISSUE TITLE
Get Access to Context from <Skeleton>

### ISSUE THREAD

**Issue by trisys3** [dvtng/react-loading-skeleton#130]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to access the theme/context values from the inner `<Skeleton>` component. This makes it hard to provide default values to `<Skeleton>` while still being able to override these defaults in an outer `<SkeletonTheme>`. The innermost `<SkeletonTheme>` overrides all ancestor context, even context it doesn't provide, meaning it isn't possible to include an app-level `<SkeletonTheme>` unless that's the only `<SkeletonTheme>`.

I would like to use this to provide default theme values for my `<Skeleton>` while still being able to override them in a wrapper `<SkeletonTheme>`, for example:

```
<SkeletonThemeWrapper baseColor='green'>
    <SkeletonWrapper />
</SkeletonThemeWrapper>;

function SkeletonWrapper({baseColor = 'red'}) {
    return <Skeleton baseColor={baseColor} />
}

function SkeletonThemeWrapper({baseColor, children}) {
    return <SkeletonTheme baseColor={baseColor}>{children}</SkeletonTheme>;
}
```

In the above, I would like the base color to be green but I'm not sure how to make that happen.

**Describe the solution you'd like**
I think being able to access the context from `<Skeleton>` would do it. This could be accomplished by exporting the context, which can be consumed with `useContext`, `contextType`, or `<Consumer>`. There are probably other ways to do this, as well.

**Describe alternatives you've considered**
There is no other way to do this without leaking information about the skeleton. For example, you could have your own theme component with context, but that kind of defeats the purpose of `<SkeletonTheme>`, especially given that the inner theme component overrides all the outer contexts, even that which isn't provided.

**Additional context**
I also found a bug where an inner `<SkeletonTheme>` overrides all ancestor context, even context it doesn't provide. This is similar to the resolved ticket I opened where explicitly defined but `undefined` `<Skeleton>` props overrode the context. This exacerbates my current problem, but it can go in a separate ticket if that's needed.

**Comment by srmagura** [comment]
I don't fully understand your use case, but I think the problem could likely be solved by getting rid of these "wrapper" components. Instead, use `Skeleton` and `SkeletonTheme` directly.

Here's how you might do an app-wide theme and then a different theme for a section of your app:

```tsx
const appSkeletonTheme = { baseColor: 'red' }

render(
    <SkeletonTheme {...appSkeletonTheme}>
        <Skeleton />
        <SkeletonTheme {...appSkeletonTheme} highlightColor="blue">
            <Skeleton />
        </SkeletonTheme>
    </SkeletonTheme>
)
```

> I also found a bug where an inner <SkeletonTheme> overrides all ancestor context, even context it doesn't provide.

This is how it is intended to work. As you know, `SkeletonTheme` just renders a `<SkeletonContext.Provider>`. And when you render a provider inside another provider, `useContext` will get the value from the closest provider.

That said, it would be possible to make nested `SkeletonTheme`s "cascade" like CSS. I just don't think this is necessary for the vast majority of use cases and might be confusing since React Context does not normally cascade. Though if a lot of people want this, we could consider it for the next major version.

**Comment by trisys3** [comment]
Got it, sorry for the noise. As I mentioned, my use case is pretty fringe.

Regarding nested themes, yeah, I realize now that nested context doesn't typically cascade, though it really should. I haven't used context too often, much less nested context.

I'll close this, though it might be good as a reference if someone else wants to do something similar.
