### ISSUE TITLE
Dark theme animation not visible

### ISSUE THREAD

**Issue by henri9813** [dvtng/react-loading-skeleton#223]
**Describe the bug**
Hello,

In light theme, the skeleton animations works as expected.
<img width="1469" alt="image" src="https://github.com/dvtng/react-loading-skeleton/assets/4645967/f6a30aa7-6bb5-4868-a7ba-4a84c30ffd7f">

**To Reproduce**
Setup a tailwind^3

Switch you in dark theme ( prefered-color-scheme ) or using classes `dark` 

**Actual Behavior**

Animation is not visible, "white on white ?"
<img width="1471" alt="image" src="https://github.com/dvtng/react-loading-skeleton/assets/4645967/f1c98702-b373-4eeb-849e-61d72909901c">

**Expected Behavior**

I should have a dark theme for this.

**Versions**

- react-loading-skeleton version: ^3.4.0
- Browser version: Safari latest version

**Additional context**

**Comment by srmagura** [comment]
The animation is probably still there, but your eyes are having trouble seeing it because of the black background.

You can use `<SkeletonTheme>` to create a dark theme for your skeletons. There is an example of dark theme in [this file](https://github.com/dvtng/react-loading-skeleton/blob/d8c1492840c273609b0dac8cbe9cc601ca8bad3c/src/__stories__/SkeletonTheme.stories.tsx#L12-L13).

**Comment by henri9813** [comment]
Hello,

Thank you for your reply;

However, how the dark mode is enabled on the skeleton ? is it native or should I configure it ?

Thanks !

**Comment by henri9813** [comment]
Why close the issue ? 

You could instead let it open and permit to community to propose a feature for this ?

**Comment by iamvinny** [comment]
I believe [dark variant ](https://tailwindcss.com/docs/dark-mode)should be included by default as most new apps have both dark and white mode.
