### ISSUE TITLE
Skeleton with Lazy Suspense

### ISSUE THREAD

**Issue by AcidRaZor** [dvtng/react-loading-skeleton#25]
Hi, just wondering if anyone got the Skeleton to work with Lazy/Suspense from 16.6?

I'm trying to do this component level as suggested, but the Lazy/Suspense kicks in and shows the loading fallback the entire time instead.

Any ideas? Should I just add a generic skeleton in there instead of per component?

**Comment by asherccohen** [comment]
Suspense normally works for something that is fetching since it's capturing a return Promise (very simply put).
It depends by your use case.

An alternative could be to crreate your own Suspense component for non-fetching elements, you can achieve this with visibility tricks (play with display: none/block) based on something internal to the component.

**Comment by srmagura** [comment]
So I think you are trying to render skeletons while `React.lazy(() => import('./MyComponent'))` is loading `MyComponent`. Putting skeletons in `MyComponent` isn't going to work because `MyComponent` isn't rendered until `React.lazy` finishes loading the code for `MyComponent`.

**Solution 1:** Render a traditional, non-skeleton loading screen as your Suspense fallback.

**Solution 2:** Make `MyComponent` take a `loading` boolean as a prop. Then:

```tsx
<Suspense fallback={<MyComponent loading />}>
    <MyComponent loading={false} />
</Suspense>
```
