### ISSUE TITLE
Support RTL animation 

### ISSUE THREAD

**Issue by saadaouad** [dvtng/react-loading-skeleton#77]
First of all I'd like to thank you for this great package,

Right now there is no support for RTL skeleton animation, is there a way to add a `direction` (`direction: string`, Defaults to `ltr`) or `rtl` (`rtl: boolean` Defaults to `false`) prop on [SkeletonTheme](https://github.com/dvtng/react-loading-skeleton/blob/master/src/skeleton-theme.js) component to deal with that?

Happy to help on that!

**Comment by saadaouad** [comment]
It will change only the element direction and not the animation

**Comment by saadaouad** [comment]
Since are you using [animation](https://github.com/dvtng/react-loading-skeleton/blob/master/src/skeleton.js#L71) CSS property, the only way to change the animation direction is to use [animation-direction](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-direction) property. 

Right now we can set that only on `Skeleton` component using `className`/`style` properties which will be repetitive if you are using many `Skeleton` components.

A better way to deal with that in my opinion is to set a new property (`direction`) on [SkeletonTheme](https://github.com/dvtng/react-loading-skeleton/blob/master/src/skeleton-theme.js) component and change the `animation-direction` value from `normal` to `reverse` according to `direction` value (`rtl`/`ltr`).

**Comment by dvtng** [comment]
Ah sorry I didn't explain my idea well. I meant that we can modify the library so that it already comes with CSS that detects if a skeleton is in a rtl document (or section), and if so apply `animation-direction: reverse` by itself. This would maintain the ethos that the skeleton should automatically adapt to the contents of your page, rather than having to manually specify the direction in some another way. It seems that the `:dir` pseudo-selector I mentioned earlier has limited browser support, but if your page is using the `dir` HTML attribute then we could still make the idea work.

**Comment by saadaouad** [comment]
I opened a PR for it @dvtng https://github.com/dvtng/react-loading-skeleton/pull/78, hopefully it will work

**Comment by jaril5976** [comment]
Hello @saadaouad @dvtng last open PR looks good to me, please merge it and issue will be fixed, we are waiting for rtl props to skeletontheme, Thanks!!

**Comment by jaril5976** [comment]
**I had fixed this issue with this**  

```
${({theme:{isRTL}}) => isRTL && css`
    .react-loading-skeleton {
      animation-direction: reverse;
    }
  `}
```
